import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <header className="bg-cyan-500 text-white p-4 fixed top-0 w-full text-start">
        <h1 className="text-3xl font-bold text-black">My Next.js App</h1>
      </header>
      <body className="min-h-full flex flex-col">{children}</body>
      <footer className="bg-cyan-500 text-white p-4 fixed bottom-0 w-full text-center">
        <p>&copy; 2023 My Next.js App. All rights reserved.</p>
      </footer>
    </html>
  );
}
